# Spring properties
spring:
  application:
     name: accounts-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      #defaultZone: http://int-eureka-001.apse2.server-web.com/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port